/* eslint-disable linebreak-style */
/* eslint-disable indent */
// eslint-disable-next-line indent
/* eslint-disable eol-last */

const categorieutenti = [
    'Sociologia',
    'Psicologia',
    'Comunicazione e marketing',
    'Sessuologia',
    'Filosofia',
    'Antropologia',
];

const passwordsemplici = [
    '123456',
    'password',
    '123456789',
    '12345',
    '12345678',
    'qwerty',
    '1234567',
    '111111',
    '1234567890',
    '123123',
    'abc123',
    '1234',
    'password1',
    'iloveyou',
    '1q2w3e4r',
    '000000',
    'qwerty123',
    'zaq12wsx',
    'dragon',
    'sunshine',
    'princess',
    'letmein',
    '654321',
    'monkey',
    '27653',
    '1qaz2wsx',
    '123321',
    'qwertyuiop',
    'superman',
    'asdfghjkl',
    '123456',
    '123456789',
    'juventus',
    'password',
    '12345678',
    'ciaociao',
    'francesca',
    'alessandro',
    'giuseppe',
    'martina',
    'francesco',
    'valentina',
    'qwertyuiop',
    'antonio',
    'stellina',
    'federico',
    'federica',
    'giovanni',
    'lorenzo',
    'asdasd',
    '123456',
    'password',
    '12345678',
    '1234567',
    'qwerty',
    '654321',
    '111111',
    '123123',
    '1234567890',
    'iloveyou',
];

const RegioniItaliane = [
    'Valle d\'Aosta ',
    'Piemonte',
    'Liguria',
    'Lombardia',
    'Trentino-Alto Adige',
    'Veneto',
    'Friuli-Venezia Giulia',
    'Emilia Romagna',
    'Toscana',
    'Umbria',
    'Marche',
    'Lazio',
    'Abruzzo',
    'Molise',
    'Campania',
    'Puglia',
    'Basilicata',
    'Calabria',
    'Sicilia',
    'Sardegna',
];
const Nazioni = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antarctica',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bermuda',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burma',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape Verde',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo, Democratic Republic',
    'Congo, Republic of the',
    'Costa Rica',
    'Cote d\'Ivoire',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'East Timor',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Greenland',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hong Kong',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea, North',
    'Korea, South',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Mongolia',
    'Morocco',
    'Monaco',
    'Mozambique',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Norway',
    'Oman',
    'Pakistan',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Samoa',
    'San Marino',
    'Sao Tome',
    'Saudi Arabia',
    'Senegal',
    'Serbia and Montenegro',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
];

module.exports = {
    categorieutenti,
    passwordsemplici,
    RegioniItaliane,
    Nazioni,
};